-- MySQL Script generated by MySQL Workbench
-- Wed May 31 18:28:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DistritoFiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DistritoFiscal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DistritoFiscal` (
  `id` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Dependencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dependencias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dependencias` (
  `id` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `atributo1` VARCHAR(255) NULL DEFAULT NULL,
  `id_distrito` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`id_distrito` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_distrito`)
    REFERENCES `mydb`.`DistritoFiscal` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`TipoSede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoSede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TipoSede` (
  `id` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sede` (
  `id` INT NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_sede_id` INT NULL DEFAULT NULL,
  `servicios` VARCHAR(255) NULL DEFAULT NULL,
  `dependencias` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`dependencias` ASC) VISIBLE,
  INDEX (`tipo_sede_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`dependencias`)
    REFERENCES `mydb`.`Dependencias` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`tipo_sede_id`)
    REFERENCES `mydb`.`TipoSede` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Servicios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Servicios` (
  `id` INT NULL DEFAULT NULL,
  `continuidadServicio` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Conectividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Conectividad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Conectividad` (
  `id` INT NULL DEFAULT NULL,
  `id_servicio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`id_servicio` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_servicio`)
    REFERENCES `mydb`.`Servicios` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`FluidoElectrico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FluidoElectrico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FluidoElectrico` (
  `id` INT NULL DEFAULT NULL,
  `id_servicio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`id_servicio` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_servicio`)
    REFERENCES `mydb`.`Servicios` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`TipoFiscalia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoFiscalia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TipoFiscalia` (
  `id` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Despacho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Despacho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Despacho` (
  `id` INT NULL DEFAULT NULL,
  `id_tipo_fiscalia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`id_tipo_fiscalia` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_tipo_fiscalia`)
    REFERENCES `mydb`.`TipoFiscalia` (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Fiscalia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fiscalia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fiscalia` (
  `id` INT NULL DEFAULT NULL,
  `categoria` VARCHAR(255) NULL DEFAULT NULL,
  `id_despacho` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`id_despacho` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_despacho`)
    REFERENCES `mydb`.`Despacho` (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
